<br /><br />
<div id="view-content">
	<p>View script for controller <b>Login</b> and script/action name <b>index</b></p>
	<!-- 
	<form method="post" action="">
	<div>
		用户名：<input type="text" name="username" placeholder="input you username"/>
	</div>
	<div>
		密  码：<input type="password" name="password" placeholder="input you password"/>
	</div>
	<div>
		<input type="button" value="登录" />
	</div>
	</form>
	 -->
	<?php 
	echo $this->loginMessage;
	echo $this->formlogin;
	?>
</div>